name: Foundry CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.8.3

      - name: Install forge-std
        run: forge install foundry-rs/forge-std --no-commit

      - name: Format check
        run: forge fmt --check

      - name: Build
        run: forge build

      - name: Unit, fuzz and invariant tests
        run: forge test -vv
